### PR TITLE
thmap_create: Test allocation, not relocation, for null.

### LINKED ISSUE #13: thmap_create tests wrong value for allocation failure
On allocation failure, the `alloc` operation returns zero, but `thmap_create` tests whether the `THMAP_GETPTR`-relocated pointer is null instead:

https://github.com/rmind/thmap/blob/8149b27f096b71ab93df00615a3b07f4dfd7e820/src/thmap.c#L896-L898

This is in contrast to all the other allocation failure tests, such as:

https://github.com/rmind/thmap/blob/8149b27f096b71ab93df00615a3b07f4dfd7e820/src/thmap.c#L312-L315

However, t_thmap.c allocates starting from zero.  So it can't actually represent failure:

https://github.com/rmind/thmap/blob/8149b27f096b71ab93df00615a3b07f4dfd7e820/src/t_thmap.c#L19-L20
https://github.com/rmind/thmap/blob/8149b27f096b71ab93df00615a3b07f4dfd7e820/src/t_thmap.c#L240-L245

### PR DESCRIPTION
**Pull request by riastradh**
Adapt test so it never returns zero on success.

fix https://github.com/rmind/thmap/issues/13

### CODE REVIEW

File: src/t_thmap.c [hunk 1]
```diff
@@ -242,13 +242,13 @@ alloc_test_wrapper(size_t len)
 	uintptr_t p = space_allocated;
 	space_allocated += roundup2(len, sizeof(void *));
 	assert(space_allocated <= sizeof(space));
-	return p;
+	return p + 4;
```
Comment (rmind) [inline src/t_thmap.c:245]: Can you please define something like `static const unsigned	space_off = 4;` after `space_allocated` and use the constant? Thanks.

File: src/thmap.c [hunk 2]
```diff
@@ -894,11 +894,11 @@ thmap_create(uintptr_t baseptr, const thmap_ops_t *ops, unsigned flags)
 	if ((thmap->flags & THMAP_SETROOT) == 0) {
 		/* Allocate the root level. */
 		root = thmap->ops->alloc(THMAP_ROOT_LEN);
-		thmap->root = THMAP_GETPTR(thmap, root);
-		if (!thmap->root) {
+		if (!root) {
```
Comment (rmind) [inline src/thmap.c:897]: Good spot.
